name: Validation pipeline

on:
  pull_request:
    branches: ["develop", "main"]

jobs:

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: haskell-actions/run-fourmolu@v11
        with:
          version: "0.17.0.0"
          
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: setup db
        run: |
          ./example/start-db.sh

      - uses: freckle/stack-action@v5
      
      - name: run benchmarks
        run: stack bench
        
      - name: build example project
        run: make build-example
